apiVersion: v1
kind: Secret
metadata:
  namespace: jitsi
  name: jitsi-config
type: Opaque
data:
  JICOFO_COMPONENT_SECRET: i1doXku9/QkDmFKB8FQemQ== # replace with valid base64 secret
  JICOFO_AUTH_PASSWORD: tIOUDjapztz/AceeP19w6Q== # replace with valid base64 secret
  JVB_AUTH_PASSWORD: wwN4uocxV4SK-wb1zNXImA # replace with valid base64 secret
  JVB_STUN_SERVERS: rO3k5vlTnvWcWlwk3IobCw # replace with valid base64 secret
  TURNCREDENTIALS_SECRET: Mj6hYTzy7OrTTGg9Y4BwdQ # replace with valid base64 secret
  TURN_HOST: e5tIojoR0ZcEcYiVP11kxg # replace with valid base64 secret
  STUN_PORT: pF4Mo1uLpKDW9qPuhYctzw # replace with valid base64 secret
  TURN_PORT: NMVSqCLrZqljt-pnG9_bgw # replace with valid base64 secret
  TURNS_PORT: rFky1JEV6px-xFfgsazAlA # replace with valid base64 secret
