apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  retention: 7d
  resources:
    requests:
      memory: 5500Mi
      cpu: 2000m
    limits:
      memory: 5500Mi
      cpu: 2000m
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: ionos-enterprise-hdd
        resources:
          requests:
            storage: 100Gi
